services:
  fastapi:
    public: true
    build: .
    replicas: 1
    environment:
      - REDIS_URI=redis-17350.c276.us-east-1-2.ec2.cloud.redislabs.com:17350 #change this REDIS_URI get it from redistogo.com
      - PYTHON_ENV=prod
      - CACHE_EXPIRATION=180
    ports:
      - 8080
    resources:
      requests:
        cpu: 500m
        memory: 1500Mi
      limits:
        cpu: 1000m
        memory: 3000Mi
